# Generated by Django 5.2.17 on 2026-09-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
