# Generated by Django 5.2.17 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_topic_x_topic_y"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="confidence",
            field=models.IntegerField(default=0),
        ),
    ]
