# Generated by Django 5.2.17 on 2026-09-20 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_topic_x_topic_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_ids', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('generating_script', 'Generating Script'), ('generating_audio', 'Generating Audio'), ('rendering', 'Rendering'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('video', models.FileField(blank=True, upload_to='videos/')),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sandbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_jobs', to='core.sandbox')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
